framework:
    router:
        resource: "%kernel.root_dir%/%kernel.application%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.application%_%kernel.environment%.log"
            level: debug