imports:
    - { resource: config.yml }
    - { resource: ../../common/config_dev.yml }

monolog:
    handlers:
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info

oro_assetic:
    css_debug:      ~
    css_debug_all:  false

#swiftmailer:
#    delivery_address: me@example.com
