imports:
    - { resource: ../../common/parameters.yml }
    - { resource: ../../common/config.yml }
    - { resource: security.yml }

framework:
    session:
        name:        B2BID_FRONT
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    port:       "%mailer_port%"
    encryption: "%mailer_encryption%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    spool:      { type: memory }
    logging:    true

# FOS User Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: OroB2B\Bundle\UserBundle\Entity\User
    group:
        group_class: OroB2B\Bundle\UserBundle\Entity\Group
    service:
        mailer: orob2b_user.mailer
    registration:
        confirmation:
            enabled: true
        form:
            type: orob2b_user_registration
    profile:
        form:
            type: orob2b_user_profile
services:
    oro_distribution.routing_loader:
        class: Oro\Bundle\DistributionBundle\Routing\OroAutoLoader
        arguments:
            - "@file_locator"
            - "@kernel"
        tags:
            - { name: routing.loader }
