imports:
    - { resource: config_prod.yml }
    - { resource: ../../common/parameters_test.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    csrf_protection: true
    profiler: { only_exceptions: false }

services:
    twig.extension.debug:
        class: Twig_Extensions_Extension_Debug
        tags:
            - { name: twig.extension }

swiftmailer:
    disable_delivery: true