imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/%kernel.application%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false