imports:
    - { resource: @OroDistributionBundle/Resources/config/security.yml }
    - { resource: ../../common/parameters.yml }
    - { resource: ../../common/config.yml }

parameters:
    console.application.class: Symfony\Bundle\FrameworkBundle\Console\Application

framework:
    session:
        name:                 BAPID_DIST

# Assetic Configuration
assetic:
    filters:
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to: "\.less$"
        cssmin:
            file: %kernel.root_dir%/%kernel.application%/Resources/php/cssmin-v3.0.1.php

# Doctrine Configuration
doctrine:
    dbal:
        default_connection:   default
        connections:
            default:
                driver:       pdo_mysql
                host:         "%database_host%"
                port:         "%database_port%"
                dbname:       "%database_name%"
                user:         "%database_user%"
                password:     "%database_password%"
                charset:      UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping:         true

# Twig Configuration
twig:
    debug:                    "%kernel.debug%"
    strict_variables:         "%kernel.debug%"

lexik_maintenance:
    driver:
        class:                Lexik\Bundle\MaintenanceBundle\Drivers\FileDriver
        options:
            file_path:        %kernel.root_dir%/cache/maintenance_lock

services:
    oro.cache.abstract:
        abstract:             true
        class:                Doctrine\Common\Cache\PhpFileCache
        arguments:            [%kernel.cache_dir%]
    twig.extension.intl:
         class:               Twig_Extensions_Extension_Intl
         tags:
             - { name: twig.extension }

oro_help:
    defaults:
        server: http://help.orocrm.com/
        prefix: Third_Party
    vendors:
        Oro:
            prefix: ~
            alias: Platform

monolog:
    handlers:
        oro_distribution:
            type: stream
            path: "%kernel.logs_dir%/%kernel.application%_%kernel.environment%.log"
            channels: oro_distribution

oro_distribution:
    composer_cache_home: "%kernel.root_dir%/../var/cache/composer"